version: '3'
services:
  nginx:
    image: nginx:1.27.3
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi-app

  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      APP_ENV: $APP_ENV
      SECRET_KEY: $SECRET_KEY
      DB_URL: $DB_URL
      SQLALCHEMY_POOL_SIZE: $SQLALCHEMY_POOL_SIZE
